CREATE TABLESPACE TlkZykovDB_tablespace
DATAFILE 'TlkZykovDB_tablespace_file.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

CREATE TEMPORARY TABLESPACE TlkZykovDB_tablespace_TEMP
TEMPFILE 'TlkZykovDB_tablespace_TEMP_file.dbf' SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED;

SELECT * FROM dba_tablespaces;

-----------------------------------------------------------

CREATE USER TLKAdmin IDENTIFIED BY AdminPass
DEFAULT TABLESPACE TlkZykovDB_tablespace
TEMPORARY TABLESPACE TlkZykovDB_tablespace_TEMP
QUOTA UNLIMITED ON TlkZykovDB_tablespace;


CREATE USER TLKAnalytic IDENTIFIED BY AnalyticPass
DEFAULT TABLESPACE TlkZykovDB_tablespace
TEMPORARY TABLESPACE TlkZykovDB_tablespace_TEMP;
--QUOTA UNLIMITED ON TlkZykovDB_tablespace;


CREATE USER TLKCustomer IDENTIFIED BY CustomerPass
DEFAULT TABLESPACE TlkZykovDB_tablespace
TEMPORARY TABLESPACE TlkZykovDB_tablespace_TEMP
QUOTA UNLIMITED ON TlkZykovDB_tablespace;


CREATE USER TLKSupplier IDENTIFIED BY SupplierPass
DEFAULT TABLESPACE TlkZykovDB_tablespace
TEMPORARY TABLESPACE TlkZykovDB_tablespace_TEMP
QUOTA UNLIMITED ON TlkZykovDB_tablespace;


CREATE USER TLKProgram IDENTIFIED BY ProgramPass
DEFAULT TABLESPACE TlkZykovDB_tablespace
TEMPORARY TABLESPACE TlkZykovDB_tablespace_TEMP
QUOTA UNLIMITED ON TlkZykovDB_tablespace;

------------------------------------------------------

-- TLKAnalytic
GRANT SELECT ON SYS.Dim_Customer TO TLKAnalytic;
GRANT SELECT ON SYS.Dim_Employee TO TLKAnalytic;
GRANT SELECT ON SYS.Dim_Time TO TLKAnalytic;
GRANT SELECT ON SYS.Dim_StoreHouse TO TLKAnalytic;
GRANT SELECT ON SYS.Dim_Product TO TLKAnalytic;
GRANT SELECT ON SYS.Dim_Supplier TO TLKAnalytic;
GRANT SELECT ON SYS.Fact_Shipment TO TLKAnalytic;
GRANT SELECT ON SYS.Fact_Arrival TO TLKAnalytic;

GRANT CREATE SESSION TO TLKAnalytic;
GRANT RESTRICTED SESSION TO TLKAnalytic;
GRANT CREATE PROCEDURE TO TLKAnalytic;

--TLKAdmin
GRANT EXECUTE ON DBMS_CRYPTO TO TLKAdmin;
GRANT CREATE SESSION TO TLKAdmin;
GRANT RESTRICTED SESSION TO TLKAdmin;
GRANT CREATE PROCEDURE TO TLKAdmin;

GRANT INSERT, SELECT ON SYS.USER_ROLE TO TLKAdmin;
GRANT INSERT, SELECT ON SYS.Dim_Employee TO TLKAdmin;
GRANT INSERT, SELECT ON SYS.Dim_StoreHouse TO TLKAdmin;
GRANT INSERT, SELECT ON SYS.Dim_Customer TO TLKAdmin;
GRANT INSERT, SELECT ON SYS.Dim_Supplier TO TLKAdmin;
GRANT SELECT, DELETE ON SYS.Fact_Shipment TO TLKAdmin;
GRANT SELECT, DELETE ON SYS.Fact_Arrival TO TLKAdmin;
GRANT SELECT, DELETE ON SYS.Dim_Product TO TLKAdmin;

SELECT * FROM DBA_SYS_PRIVS WHERE GRANTEE = 'TLKADMIN';
SELECT * FROM USER_TAB_PRIVS WHERE GRANTEE = 'TLKADMIN';

--TLKCustomer

GRANT SELECT ON SYS.Dim_Employee TO TLKCustomer;
GRANT SELECT ON SYS.Dim_StoreHouse TO TLKCustomer;
GRANT INSERT, select ON SYS.Dim_Time TO TLKCustomer;
GRANT INSERT, select ON SYS.Dim_Product TO TLKCustomer;
GRANT INSERT ON SYS.Fact_Shipment TO TLKCustomer;

GRANT CREATE SESSION TO TLKCustomer;
GRANT RESTRICTED SESSION TO TLKCustomer;
GRANT CREATE PROCEDURE TO TLKCustomer;

--TLKSupplier

GRANT SELECT ON SYS.Dim_Employee TO TLKSupplier;
GRANT SELECT ON SYS.Dim_StoreHouse TO TLKSupplier;
GRANT INSERT, select ON SYS.Dim_Time TO TLKSupplier;
GRANT INSERT, select ON SYS.Dim_Product TO TLKSupplier;
GRANT INSERT ON SYS.Fact_Arrival TO TLKSupplier;


GRANT CREATE SESSION TO TLKSupplier;
GRANT RESTRICTED SESSION TO TLKSupplier;
GRANT CREATE PROCEDURE TO TLKSupplier;

--TLKProgram
GRANT EXECUTE ON DBMS_CRYPTO TO TLKProgram;
GRANT CREATE SESSION TO TLKProgram;
GRANT RESTRICTED SESSION TO TLKProgram;
GRANT SELECT ON User_Role TO TLKProgram;
GRANT CREATE PROCEDURE TO TLKProgram;


SELECT *
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'TLKCUSTOMER';

SELECT *
FROM DBA_TAB_PRIVS
WHERE GRANTEE = 'TLKCUSTOMER';